import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import  '../styles/globals.css';
import Prueba2 from '../components/Prueba2'
import Prueba3 from '../components/Prueba3'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <html lang="en">
      <body className={inter.className}>
       
        <Prueba2/>
        <Prueba3/>
        <br/>
        
        {children}</body>
    </html>
  )
}
